spring:
  datasource: 
    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    username: GMDMF
    password: gmdmf
    platform: tibero
    initialization-mode: always
  mvc: 
   hiddenmethod:
    filter:
     enabled: true
   view: 
    prefix: /WEB-INF/views/
    suffix: .jsp
   
server: 
  port: 9090

#mybatis:  


mybatis: 
  type-aliases-package: com.example.work.board.model
#  config-location: classpath:mybatis-config.xml
  mapper-locations: mapper/*.xml
  configuration: 
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30